### ISSUE TITLE
What's the mxnet_predict ?

### ISSUE THREAD

**Issue by FernWan** [haria/mxnet-multi-task-example#2] opened 2016-10-30 13:50 UTC
hello,
I have done the experiment follow your opinions,but I have an error:

 from mxnet_predict import Predictor
ImportError: No module named mxnet_predict

What should I do to solve the problem?

**Comment by FernWan** [comment] 2016-10-31 12:18
I have solved the problem about mxnet_predict ,but I have another problem which is RuntimeError: src/ndarry/ndarry.cc:669Check failed : (dshape.Size()==(size)Memory size do not match)
How can I solve the problem?

**Comment by guosusu** [comment] 2018-03-06 02:28
I meet the same problem, I can not find module mxnet_predict and get_data, Could you tell me how to solve it?Thanks! @FernWan @hariag

**Comment by hariag** [comment] 2018-03-06 11:32
Duplicate of #3

**Closed as completed by hariag** 2018-03-06 11:32 UTC
